/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import Database.DatabaseConnection;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    DatabaseConnection db;
    DashBoard DB;
    Pattern pattern = Pattern.compile("[A-Za-z0-9_ ]+");
    Pattern pattern2 = Pattern.compile("[0-9]+");
    Pattern pattern3 = Pattern.compile("[A-Z0-9]+");
    
    public Customer(DashBoard DB) throws SQLException {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        db = new DatabaseConnection(InventorySystem.con);
        this.DB = DB;
    }

    private Customer() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LCustomerName = new javax.swing.JLabel();
        TFCustomerName = new javax.swing.JTextField();
        LMobileNo = new javax.swing.JLabel();
        TFMobileNo = new javax.swing.JTextField();
        LAadharNo = new javax.swing.JLabel();
        LGSTINNo = new javax.swing.JLabel();
        LAddress = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        TFGSTINNo = new javax.swing.JTextField();
        TFAadharNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 37, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 539));
        jPanel1.setLayout(null);

        LCustomerName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        LCustomerName.setText("Customer Name :");
        LCustomerName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LCustomerName);
        LCustomerName.setBounds(20, 90, 110, 30);

        TFCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFCustomerNameKeyReleased(evt);
            }
        });
        jPanel1.add(TFCustomerName);
        TFCustomerName.setBounds(150, 90, 270, 30);

        LMobileNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LMobileNo.setForeground(new java.awt.Color(255, 255, 255));
        LMobileNo.setText("Mobile No.           :");
        LMobileNo.setToolTipText("");
        jPanel1.add(LMobileNo);
        LMobileNo.setBounds(20, 140, 107, 30);

        TFMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMobileNoActionPerformed(evt);
            }
        });
        TFMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFMobileNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFMobileNo);
        TFMobileNo.setBounds(150, 140, 270, 30);

        LAadharNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAadharNo.setForeground(new java.awt.Color(255, 255, 255));
        LAadharNo.setText("Aadhar No           :");
        jPanel1.add(LAadharNo);
        LAadharNo.setBounds(20, 390, 110, 30);

        LGSTINNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LGSTINNo.setForeground(new java.awt.Color(255, 255, 255));
        LGSTINNo.setText("GSTIN No            :");
        jPanel1.add(LGSTINNo);
        LGSTINNo.setBounds(20, 340, 110, 30);

        LAddress.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAddress.setForeground(new java.awt.Color(255, 255, 255));
        LAddress.setText("Address                 :");
        jPanel1.add(LAddress);
        LAddress.setBounds(21, 240, 110, 27);

        LEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email                      :");
        jPanel1.add(LEmail);
        LEmail.setBounds(20, 190, 110, 30);
        jPanel1.add(TFEmail);
        TFEmail.setBounds(150, 190, 266, 30);

        TFGSTINNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFGSTINNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFGSTINNo);
        TFGSTINNo.setBounds(150, 340, 266, 30);
        jPanel1.add(TFAadharNo);
        TFAadharNo.setBounds(150, 390, 265, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 450, 84, 32);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 450, 84, 32);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADD CUSTOMER");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 11, 410, 59);

        TFAddress.setColumns(20);
        TFAddress.setLineWrap(true);
        TFAddress.setRows(5);
        TFAddress.setTabSize(4);
        jScrollPane1.setViewportView(TFAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 240, 260, 71);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 539);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DB.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TFMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMobileNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] Customer = new String[6];
        Customer[0] = TFCustomerName.getText();
        long temp = 0;
        try {
            temp = Long.parseLong(TFMobileNo.getText());
            Customer[1] = String.valueOf(temp);
        } catch (NumberFormatException numberFormatException) {
            Customer[1] = "";
        }
        
        Customer[2] = TFEmail.getText();
        Customer[3] = TFAddress.getText();
        Customer[4] = TFGSTINNo.getText();
        Customer[5] = TFAadharNo.getText();
        
        for(int i=0;i<Customer.length;i++)
        {
            Customer[i].trim();
        }
            
        if(Customer[0] == null || Customer[0].equals(""))
        {
            LCustomerName.setForeground(Color.red);
        }else if(Customer[1].length() != 10)
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.red);
        }else if(Customer[2] == null || Customer[2].equals(""))
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LEmail.setForeground(Color.red);
        }else if(Customer[3] == null || Customer[3].equals(""))
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LEmail.setForeground(Color.WHITE);
            LAddress.setForeground(Color.red);
        }else if(Customer[4].length() != 15)
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LEmail.setForeground(Color.WHITE);
            LAddress.setForeground(Color.WHITE);
            LGSTINNo.setForeground(Color.red);
        }else if(Customer[5].length() != 12)
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LEmail.setForeground(Color.WHITE);
            LAddress.setForeground(Color.WHITE);
            LGSTINNo.setForeground(Color.WHITE);
            LAadharNo.setForeground(Color.red);
        }else{
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LEmail.setForeground(Color.WHITE);
            LAddress.setForeground(Color.WHITE);
            LGSTINNo.setForeground(Color.WHITE);
            LAadharNo.setForeground(Color.WHITE);
            try {
                db.Customer(Customer);
                TFCustomerName.setText("");
                TFMobileNo.setText("");
                TFEmail.setText("");
                TFAddress.setText("");
                TFGSTINNo.setText("");
                TFAadharNo.setText("");
                
            } catch (SQLException ex) {
                Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        DB.setCustomerName();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCustomerNameKeyReleased
        // TODO add your handling code here:
        String name = TFCustomerName.getText();
        boolean valid = (name != null) && pattern.matcher(name).matches();
        if(!valid)
        {
            try {
                name = name.substring(0, name.length() - 1);
            } catch (Exception e) {
            }
            TFCustomerName.setText(name);
        }
    }//GEN-LAST:event_TFCustomerNameKeyReleased

    private void TFMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMobileNoKeyReleased
        // TODO add your handling code here:
        String MobileNo = TFMobileNo.getText();
        boolean valid = (MobileNo != null) && pattern2.matcher(MobileNo).matches();
        if(!valid)
        {
            try {
                MobileNo = MobileNo.substring(0, MobileNo.length() - 1);
            } catch (Exception e) {
            }
            TFMobileNo.setText(MobileNo);
        }
    }//GEN-LAST:event_TFMobileNoKeyReleased

    private void TFGSTINNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFGSTINNoKeyReleased
        // TODO add your handling code here:
        String GSTINNo = TFGSTINNo.getText();
        boolean valid = (GSTINNo != null) && pattern3.matcher(GSTINNo).matches();
        if(!valid)
        {
            try {
                GSTINNo = GSTINNo.substring(0, GSTINNo.length() - 1);
            } catch (Exception e) {
            }
            TFGSTINNo.setText(GSTINNo);
        }
    }//GEN-LAST:event_TFGSTINNoKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        DB.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAadharNo;
    private javax.swing.JLabel LAddress;
    private javax.swing.JLabel LCustomerName;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LGSTINNo;
    private javax.swing.JLabel LMobileNo;
    private javax.swing.JTextField TFAadharNo;
    private javax.swing.JTextArea TFAddress;
    private javax.swing.JTextField TFCustomerName;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFGSTINNo;
    private javax.swing.JTextField TFMobileNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
