/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aman Manmode
 */
public class DataBaseBackup extends javax.swing.JFrame {

    /**
     * Creates new form DataBaseBackup
     */
    DashBoard DB;
    public DataBaseBackup(DashBoard DB) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        this.DB = DB;
    }

    private DataBaseBackup() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFPath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 37, 45));
        jPanel1.setLayout(null);

        TFPath.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(TFPath);
        TFPath.setBounds(30, 60, 380, 30);

        jButton1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton1.setText("Backup");
        jButton1.setToolTipText("");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 120, 110, 30);

        jButton2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton2.setText("Browse");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 60, 120, 30);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Path");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 40, 20);

        jButton3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jButton3.setText("Restore");
        jButton3.setToolTipText("");
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 120, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser js = new JFileChooser();
        String txtbackuppath = null;
        js.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                  
        int r = js.showSaveDialog(DB);
        
        if(r == JFileChooser.APPROVE_OPTION)
        {
            txtbackuppath = js.getSelectedFile().getAbsolutePath();
            txtbackuppath = txtbackuppath.replace("\\", "/");
            TFPath.setText(txtbackuppath);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!TFPath.getText().equals(""))
        {
            Process p = null;
            try {

                Runtime runtime = Runtime.getRuntime();
                p = runtime.exec("C:/Program Files (x86)/MySQL/MySQL Server 5.1/bin/mysqldump.exe -uroot -proot --add-drop-database -B inventorysystem -r "+TFPath.getText()+"/InventoryManagement.sql");
                //change the dbpass and dbname with your dbpass and dbname
                int processComplete = p.waitFor();

                if (processComplete == 0) {
                    JOptionPane.showMessageDialog(this, "Backup created successfully");
                    DB.setEnabled(true);
                    DB.DatabaseBackupCount = 0;
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Could not create the backup...!!!");
                }
    //            System.out.println(txtbackuppath);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        DB.DatabaseBackupCount = 0;
        DB.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//       String[] executeCmd = new String[]{"C:/Program Files (x86)/MySQL/MySQL Server 5.1/bin/mysql.exe", "inventorymanagement", "-u" + "root", "-p" + "root", "-e", " source " + TFPath.getText()};
//
//        /*NOTE: processComplete=0 if correctly executed, will contain other values if not*/
//        Process runtimeProcess = null;
//        try {
//            runtimeProcess = Runtime.getRuntime().exec(executeCmd);
//            int processComplete = runtimeProcess.waitFor();
//            if (processComplete == 0) {
//                JOptionPane.showMessageDialog(null, "Successfully restored from SQL");
//            } else {
//                JOptionPane.showMessageDialog(null, "Error at restoring");
//            }
//            
//        } catch (IOException ex) {
//            Logger.getLogger(DataBaseBackup.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(DataBaseBackup.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        /*NOTE: processComplete=0 if correctly executed, will contain other values if not*/
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBaseBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBaseBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBaseBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBaseBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBaseBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFPath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
