/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import Database.DatabaseConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jfree.data.gantt.Task;
/**
 *
 * @author user
 */
public class LoginPage extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginPage
     */
    DatabaseConnection db;
    DashBoard DB = null;
    public LoginPage() throws InterruptedException, SQLException {
        initComponents();
        db = new DatabaseConnection(InventorySystem.con);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        jPanel2.setBackground(new Color(255, 255, 255, 100));
        
//        TFUserID.
        jLabel1.setOpaque(true);
//        jLabel1.setBorder(new RoundedBorder(Color.black, 10));
        jLabel4.setOpaque(true);
        jLabel2.setSize(1366, 728);
        
        TFUserID.setFocusable(false);
        TFPassword.setFocusable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        TFUserID = new javax.swing.JTextField();
        Lable4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));
        setUndecorated(true);
        getContentPane().setLayout(null);

        CloseButton.setBackground(new java.awt.Color(255, 51, 51));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-close-window-30.png"))); // NOI18N
        CloseButton.setBorder(null);
        CloseButton.setFocusable(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton);
        CloseButton.setBounds(1330, 10, 30, 30);

        jPanel2.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-lock-38.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 210, 40, 38);

        jLabel8.setBackground(new java.awt.Color(0, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-businessman-38.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 160, 40, 40);

        TFPassword.setBackground(new java.awt.Color(180, 237, 251));
        TFPassword.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        TFPassword.setForeground(new java.awt.Color(0, 102, 204));
        TFPassword.setText("password");
        TFPassword.setBorder(null);
        TFPassword.setOpaque(false);
        TFPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFPasswordFocusLost(evt);
            }
        });
        TFPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFPasswordMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFPasswordMousePressed(evt);
            }
        });
        jPanel2.add(TFPassword);
        TFPassword.setBounds(110, 210, 270, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-open-box-100.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 20, 100, 90);

        TFUserID.setBackground(new java.awt.Color(180, 237, 251));
        TFUserID.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        TFUserID.setForeground(new java.awt.Color(0, 102, 204));
        TFUserID.setText("username");
        TFUserID.setToolTipText("");
        TFUserID.setBorder(null);
        TFUserID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFUserID.setName(""); // NOI18N
        TFUserID.setOpaque(false);
        TFUserID.setVerifyInputWhenFocusTarget(false);
        TFUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFUserIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFUserIDFocusLost(evt);
            }
        });
        TFUserID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TFUserIDMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TFUserIDMousePressed(evt);
            }
        });
        TFUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFUserIDActionPerformed(evt);
            }
        });
        TFUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFUserIDKeyReleased(evt);
            }
        });
        jPanel2.add(TFUserID);
        TFUserID.setBounds(110, 160, 270, 40);

        Lable4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Lable4.setForeground(new java.awt.Color(0, 0, 204));
        Lable4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lable4.setText("DASHBOARD");
        jPanel2.add(Lable4);
        Lable4.setBounds(210, 100, 160, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("LOGIN TO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 100, 130, 50);

        jLabel1.setBackground(new java.awt.Color(180, 237, 251));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 160, 310, 40);

        jLabel4.setBackground(new java.awt.Color(180, 237, 251));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 210, 310, 40);

        Login.setBackground(new java.awt.Color(82, 221, 250));
        Login.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setOpaque(true);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginMousePressed(evt);
            }
        });
        jPanel2.add(Login);
        Login.setBounds(70, 270, 310, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(440, 180, 460, 360);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginPage/background-3246124_1920.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void TFUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUserIDActionPerformed

    private void TFUserIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUserIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFUserIDKeyReleased

    private void TFUserIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFUserIDFocusGained
        // TODO add your handling code here
        String UserID = TFUserID.getText();
        if(UserID.equals("username"))
        {
            TFUserID.setText("");
        }
    }//GEN-LAST:event_TFUserIDFocusGained

    private void TFPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFPasswordFocusLost
        // TODO add your handling code here:
        String password = TFPassword.getText();
        if(password.equals(""))
        {
            TFPassword.setText("password");
        }
    }//GEN-LAST:event_TFPasswordFocusLost

    private void TFUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFUserIDFocusLost
        // TODO add your handling code here:
        String UserID = TFUserID.getText();
        if(UserID.equals(""))
        {
            TFUserID.setText("username");
        }
    }//GEN-LAST:event_TFUserIDFocusLost

    private void TFPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFPasswordFocusGained
        // TODO add your handling code here:
        String password = TFPassword.getText();
        if(password.equals("password"))
        {
            TFPassword.setText("");
        }
    }//GEN-LAST:event_TFPasswordFocusGained

    private void TFUserIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUserIDMouseEntered
        // TODO add your handling code here:
        TFUserID.setFocusable(true);
        
    }//GEN-LAST:event_TFUserIDMouseEntered

    private void TFUserIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFUserIDMousePressed
        // TODO add your handling code here:
        TFUserID.setFocusable(true);
        TFPassword.setFocusable(true);
    }//GEN-LAST:event_TFUserIDMousePressed

    private void TFPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFPasswordMousePressed
        // TODO add your handling code here:
        TFPassword.setFocusable(true);
        TFUserID.setFocusable(true);
    }//GEN-LAST:event_TFPasswordMousePressed

    private void TFPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TFPasswordMouseEntered
        // TODO add your handling code here:
        TFPassword.setFocusable(true);
    }//GEN-LAST:event_TFPasswordMouseEntered

    private void LoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMousePressed
        // TODO add your handling code here:
        Login.setBackground(new Color(54, 147, 166));
        String Password = null;
        String EPassword = TFPassword.getText().trim();
        String UserID = TFUserID.getText().trim();
        try {
            Password = db.AdminUserIDandPassword(UserID);
        } catch (SQLException ex) {
//            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(Password.equals(""))
        {
            try {
                Password = db.getEmpPassword(UserID);
            } catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(Password.equals(""))
            {
                JOptionPane.showMessageDialog(null, "Wrong UserID");
            }else{
                try {
                    DB = new DashBoard("Employee",UserID);
                } catch (Exception ex) {
    //                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                DB.setSize(1366,728);
                DB.setVisible(true);
                DB.setExtendedState(DB.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                DB.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            }
        }else if(Password.equals(EPassword)){     
            try {

                DB = new DashBoard("Admin",UserID);
            } catch (Exception ex) {
//                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            DB.setSize(1366,728);
            DB.setVisible(true);
            DB.setExtendedState(DB.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            DB.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Wrong Password");
        } 
        Login.setBackground(new Color(82, 221, 250));
        Login.setOpaque(true);
    }//GEN-LAST:event_LoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        new LoginPage().setVisible(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel Lable4;
    private javax.swing.JLabel Login;
    private javax.swing.JPasswordField TFPassword;
    private javax.swing.JTextField TFUserID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setColor(Color color) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void fillRect(int i, int i0, int width, int height) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
