/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import Database.DatabaseConnection;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
/**
 *
 * @author user
 */
public class NewPersonUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    NewPersonUpdate UCM;
    DatabaseConnection db;
    DashBoard DB;
    String[] NewPersonD = new String[9];
    String NewPersonName;
    String WhichPanel;
    ButtonGroup BG;
    
    Pattern pattern = Pattern.compile("[A-Za-z0-9_ ]+");
    Pattern pattern2 = Pattern.compile("[0-9]+");
    Pattern pattern3 = Pattern.compile("[A-Z0-9]+");
    Pattern pattern4 = Pattern.compile("[0-9.]+");
    public NewPersonUpdate(String NewPerson,String WhichPanel,DashBoard DB) throws SQLException {
        initComponents();
        db = new DatabaseConnection(InventorySystem.con);
        this.DB = DB;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        this.NewPersonD = NewPersonD;
        this.DB.VCustomerUCount = 1;
        UCM = this;
        BG = new ButtonGroup();
        BG.add(RBToPay);
        BG.add(RBToReceive);
        
        Vector<String> v = new Vector<String>();
        if(WhichPanel.equals("PersonPay"))
        {
            v = db.PersonToPayDforUpdate(NewPerson);
            if(Double.valueOf(v.get(4)) == 0)
            {
                LDue.setText("Due");
                RBToPay.setEnabled(true);
                RBToReceive.setEnabled(true);
                RBToPay.setSelected(true);
            }else{
                LDue.setText("To Pay");
                RBToPay.setEnabled(true);
                RBToReceive.setEnabled(true);
                RBToPay.setSelected(true);
            }
        }else if(WhichPanel.equals("PersonReceive"))
        {
            v = db.PersonToReceiveDforUpdate(NewPerson);
            if(Double.valueOf(v.get(4)) == 0)
            {
                LDue.setText("Due");
                RBToPay.setEnabled(true);
                RBToReceive.setEnabled(true);
                RBToReceive.setSelected(true);
            }else{
                LDue.setText("To Receive");
                RBToPay.setEnabled(true);
                RBToReceive.setEnabled(true);
                RBToReceive.setSelected(true);
            }
        }
        
        this.WhichPanel = WhichPanel;
        TFNewPersonName.setText(v.get(0).toString());
        NewPersonName = NewPerson;
        TFMobileNo.setText(v.get(1).toString());
        TFEmail.setText(v.get(2).toString());
        TFAddress.setText(v.get(3).toString());
        TFDue.setText(v.get(4).toString());
        TFAmount.setText("0.00");
        TFTotalDue.setText("");
        
    }

    private NewPersonUpdate() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LCustomerName = new javax.swing.JLabel();
        TFNewPersonName = new javax.swing.JTextField();
        LMobileNo = new javax.swing.JLabel();
        TFMobileNo = new javax.swing.JTextField();
        LAddress = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFAddress = new javax.swing.JTextArea();
        LAmount = new javax.swing.JLabel();
        TFAmount = new javax.swing.JTextField();
        LTotal = new javax.swing.JLabel();
        TFTotalDue = new javax.swing.JTextField();
        LDue = new javax.swing.JLabel();
        TFDue = new javax.swing.JTextField();
        RBToReceive = new javax.swing.JRadioButton();
        RBToPay = new javax.swing.JRadioButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 37, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 539));
        jPanel1.setLayout(null);

        LCustomerName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        LCustomerName.setText("Person Name :");
        LCustomerName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LCustomerName);
        LCustomerName.setBounds(20, 80, 110, 30);

        TFNewPersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFNewPersonNameKeyReleased(evt);
            }
        });
        jPanel1.add(TFNewPersonName);
        TFNewPersonName.setBounds(150, 80, 270, 30);

        LMobileNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LMobileNo.setForeground(new java.awt.Color(255, 255, 255));
        LMobileNo.setText("Mobile No.           :");
        LMobileNo.setToolTipText("");
        jPanel1.add(LMobileNo);
        LMobileNo.setBounds(20, 130, 107, 30);

        TFMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMobileNoActionPerformed(evt);
            }
        });
        TFMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFMobileNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFMobileNo);
        TFMobileNo.setBounds(150, 130, 270, 30);

        LAddress.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAddress.setForeground(new java.awt.Color(255, 255, 255));
        LAddress.setText("Address                 :");
        jPanel1.add(LAddress);
        LAddress.setBounds(20, 230, 110, 27);

        LEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email                      :");
        jPanel1.add(LEmail);
        LEmail.setBounds(20, 180, 110, 30);
        jPanel1.add(TFEmail);
        TFEmail.setBounds(150, 180, 270, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 490, 100, 32);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 490, 100, 32);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE PERSON");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 11, 410, 59);

        TFAddress.setColumns(20);
        TFAddress.setLineWrap(true);
        TFAddress.setRows(5);
        TFAddress.setTabSize(4);
        jScrollPane1.setViewportView(TFAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 230, 270, 71);

        LAmount.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAmount.setForeground(new java.awt.Color(255, 255, 255));
        LAmount.setText("Amount :");
        jPanel1.add(LAmount);
        LAmount.setBounds(80, 430, 60, 30);

        TFAmount.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFAmountKeyReleased(evt);
            }
        });
        jPanel1.add(TFAmount);
        TFAmount.setBounds(150, 430, 80, 27);

        LTotal.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LTotal.setForeground(new java.awt.Color(255, 255, 255));
        LTotal.setText("Total Due :");
        jPanel1.add(LTotal);
        LTotal.setBounds(260, 430, 70, 30);

        TFTotalDue.setEditable(false);
        TFTotalDue.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(TFTotalDue);
        TFTotalDue.setBounds(340, 430, 80, 27);

        LDue.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LDue.setForeground(new java.awt.Color(255, 255, 255));
        LDue.setText("Pay Due");
        jPanel1.add(LDue);
        LDue.setBounds(150, 310, 100, 31);

        TFDue.setEditable(false);
        TFDue.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFDue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDueKeyReleased(evt);
            }
        });
        jPanel1.add(TFDue);
        TFDue.setBounds(150, 340, 80, 27);

        RBToReceive.setBackground(new java.awt.Color(32, 37, 45));
        RBToReceive.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        RBToReceive.setForeground(new java.awt.Color(255, 255, 255));
        RBToReceive.setText("To Receive");
        RBToReceive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RBToReceive.setRequestFocusEnabled(false);
        jPanel1.add(RBToReceive);
        RBToReceive.setBounds(210, 400, 90, 23);

        RBToPay.setBackground(new java.awt.Color(32, 37, 45));
        RBToPay.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        RBToPay.setForeground(new java.awt.Color(255, 255, 255));
        RBToPay.setText("To Pay");
        RBToPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RBToPay.setRequestFocusEnabled(false);
        RBToPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBToPayActionPerformed(evt);
            }
        });
        jPanel1.add(RBToPay);
        RBToPay.setBounds(140, 400, 70, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DB.NewPersonUpdateCount = 0;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    int CloseOpration()
    {
        
        DB.NewPersonUpdateCount = 0;
        this.dispose();
        return 0;
    }
    private void TFMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMobileNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] NewPerson = new String[7];
        NewPerson[0] = TFNewPersonName.getText();
        long temp = 0;
        try {
            temp = Long.parseLong(TFMobileNo.getText());
            NewPerson[1] = String.valueOf(temp);
        } catch (NumberFormatException numberFormatException) {
            NewPerson[1] = "";
        }
        
        String TransactionTempvariable;
        NewPerson[2] = TFEmail.getText();
        NewPerson[3] = TFAddress.getText();
        double PreDue = Double.valueOf(TFDue.getText());
        double Amount = Double.valueOf(TFAmount.getText());
        double TotalDue = 0;
        if(LDue.getText().equals("Due"))
        {
            if(RBToPay.isSelected())
            {
                TotalDue = Amount;
                NewPerson[5] = "ToPay";
                TransactionTempvariable = "Taken";
                
            }else{
                TotalDue = Amount;
                NewPerson[5] = "ToReceive";
                TransactionTempvariable = "Given";
            }
        }else if(LDue.getText().equals("To Pay"))
        {
            if(RBToPay.isSelected())
            {
                TotalDue = PreDue - Amount;
                NewPerson[5] = "ToPay";
                TransactionTempvariable = "Given";
            }else{
                TotalDue = PreDue + Amount;
                NewPerson[5] = "ToPay";
                TransactionTempvariable = "Taken";
            }
        }else{
            if(RBToPay.isSelected())
            {
                TotalDue = PreDue + Amount;
                NewPerson[5] = "ToReceive";
                TransactionTempvariable = "Given";
            }else{
                TotalDue = PreDue - Amount;
                NewPerson[5] = "ToReceive";
                TransactionTempvariable = "Taken";
            }
        }
        
        NewPerson[4] = String.valueOf(TotalDue);
        //System.out.println(NewPerson[4]);
        NewPerson[6] = this.NewPersonName;
        TFTotalDue.setText(String.valueOf(TotalDue));
        
        for(int i=0;i<NewPerson.length;i++)
        {
            NewPerson[i].trim();
        }
            
        if(NewPerson[0] == null || NewPerson[0].equals(""))
        {
            LCustomerName.setForeground(Color.red);
        }else if(NewPerson[1].length() != 10)
        {
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.red);
        }else if(TFAmount.getText() == null || TFAmount.getText().equals("")){
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LAmount.setForeground(Color.red);
        }else{
            LCustomerName.setForeground(Color.WHITE);
            LMobileNo.setForeground(Color.WHITE);
            LAmount.setForeground(Color.WHITE);

            try {
                db.NewPersonDUpdate(NewPerson);
                String[] TransactionD = new String[4];
                TransactionD[0] = NewPerson[0];
                TransactionD[1] = "NewPerson";
                TransactionD[2] = TransactionTempvariable;
                TransactionD[3] = TFAmount.getText();
                db.TransactionTable(TransactionD);
                if(WhichPanel.equals("PersonPay"))
                {
                    DB.RefreshPersonToPay();
                }else if(WhichPanel.equals("PersonReceive"))
                {
                    DB.RefreshPersonToReceive();
                }
                JOptionPane.showMessageDialog(null, "Person Details Updated Successfully");
                DB.NewPersonUpdateCount = 0;
                this.dispose();
                
            } catch (SQLException ex) {
                Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAmountKeyReleased
        // TODO add your handling code here:
        String due = TFAmount.getText();
        try {
            double temp = Double.valueOf(due);
            LAmount.setForeground(Color.WHITE);
        } catch (Exception e) {
            LAmount.setForeground(Color.red);
        }
        
        String Amount = TFAmount.getText();
        boolean valid = (Amount != null) && pattern4.matcher(Amount).matches();
        if(!valid)
        {
            try {
                Amount = Amount.substring(0, Amount.length() - 1);
            } catch (Exception e) {
            }
            TFAmount.setText(Amount);
        }
    }//GEN-LAST:event_TFAmountKeyReleased

    private void TFDueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDueKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDueKeyReleased

    private void RBToPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBToPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBToPayActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        DB.NewPersonUpdateCount = 0;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void TFNewPersonNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNewPersonNameKeyReleased
        // TODO add your handling code here:
        String name = TFNewPersonName.getText();
        boolean valid = (name != null) && pattern.matcher(name).matches();
        if(!valid)
        {
            try {
                name = name.substring(0, name.length() - 1);
            } catch (Exception e) {
            }
            TFNewPersonName.setText(name);
        }
    }//GEN-LAST:event_TFNewPersonNameKeyReleased

    private void TFMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMobileNoKeyReleased
        // TODO add your handling code here:
        String MobileNo = TFMobileNo.getText();
        boolean valid = (MobileNo != null) && pattern2.matcher(MobileNo).matches();
        if(!valid)
        {
            try {
                MobileNo = MobileNo.substring(0, MobileNo.length() - 1);
            } catch (Exception e) {
            }
            TFMobileNo.setText(MobileNo);
        }
    }//GEN-LAST:event_TFMobileNoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPersonUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPersonUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPersonUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPersonUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPersonUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAddress;
    private javax.swing.JLabel LAmount;
    private javax.swing.JLabel LCustomerName;
    private javax.swing.JLabel LDue;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LMobileNo;
    private javax.swing.JLabel LTotal;
    private javax.swing.JRadioButton RBToPay;
    private javax.swing.JRadioButton RBToReceive;
    private javax.swing.JTextArea TFAddress;
    private javax.swing.JTextField TFAmount;
    private javax.swing.JTextField TFDue;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFMobileNo;
    private javax.swing.JTextField TFNewPersonName;
    private javax.swing.JTextField TFTotalDue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
