/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import Database.DatabaseConnection;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;

/**
 *
 * @author user
 */
public class UpdateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    DatabaseConnection db;
    DashBoard DB;
    ButtonGroup BG;
    SimpleDateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
    Pattern pattern = Pattern.compile("[A-Za-z0-9_ ]+");
    Pattern pattern2 = Pattern.compile("[0-9]+");
    Pattern pattern3 = Pattern.compile("[A-Z0-9]+");
    Pattern pattern4 = Pattern.compile("[0-9.]+");
    String ActiveEmp;
    String EmpID;
    public UpdateEmployee(String EmpID,DashBoard DB) throws SQLException {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        db = new DatabaseConnection(InventorySystem.con);
        this.DB = DB;
        this.EmpID = EmpID;
       
        Vector<String> v = db.UpdateEmployee(this.EmpID);
        BG = new ButtonGroup();
        
        BG.add(UERBActiveEmp);
        BG.add(UERBNotWorking);
        
        TFCustomerName.setText(v.get(0));
        TFMobileNo.setText(v.get(3));
        TFEmail.setText(v.get(4));
        TFAddress.setText(v.get(5));
        TFSalary.setText(v.get(6));
        Date dt = null;
        try {
            dt = new Date(Integer.parseInt(v.get(1).substring(0, 4))-1900, (Integer.parseInt(v.get(1).substring(5, 7)))-1, Integer.parseInt(v.get(1).substring(8, 10)));
        } catch (Exception e) {
            dt = null;
        }
        DateOfBirth.setDate(dt);
        try {
            dt = new Date(Integer.parseInt(v.get(2).substring(0, 4))-1900, (Integer.parseInt(v.get(2).substring(5, 7)))-1, Integer.parseInt(v.get(2).substring(8, 10)));
        } catch (Exception e) {
            dt = null;
        }
        DateOfJoining.setDate(dt);
        
        if(v.get(7).equals("ActiveEmployee"))
        {
            UERBActiveEmp.setSelected(true);
            ActiveEmp = "true";
        }else{
            UERBNotWorking.setSelected(true);
            ActiveEmp = "false";
        }
    }

    private UpdateEmployee() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LPersonName = new javax.swing.JLabel();
        TFCustomerName = new javax.swing.JTextField();
        LMobileNo = new javax.swing.JLabel();
        TFMobileNo = new javax.swing.JTextField();
        LAddress = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFAddress = new javax.swing.JTextArea();
        LDateofBirth = new javax.swing.JLabel();
        DateOfBirth = new com.toedter.calendar.JDateChooser();
        LSalary = new javax.swing.JLabel();
        TFSalary = new javax.swing.JTextField();
        LDateofJoining = new javax.swing.JLabel();
        DateOfJoining = new com.toedter.calendar.JDateChooser();
        LSalary1 = new javax.swing.JLabel();
        UERBActiveEmp = new javax.swing.JRadioButton();
        UERBNotWorking = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 37, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 539));
        jPanel1.setLayout(null);

        LPersonName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LPersonName.setForeground(new java.awt.Color(255, 255, 255));
        LPersonName.setText("Employee Name :");
        LPersonName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LPersonName);
        LPersonName.setBounds(20, 80, 110, 30);

        TFCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFCustomerNameKeyReleased(evt);
            }
        });
        jPanel1.add(TFCustomerName);
        TFCustomerName.setBounds(150, 80, 270, 30);

        LMobileNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LMobileNo.setForeground(new java.awt.Color(255, 255, 255));
        LMobileNo.setText("Mobile No.           :");
        LMobileNo.setToolTipText("");
        jPanel1.add(LMobileNo);
        LMobileNo.setBounds(20, 230, 110, 30);

        TFMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMobileNoActionPerformed(evt);
            }
        });
        TFMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFMobileNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFMobileNo);
        TFMobileNo.setBounds(150, 230, 270, 30);

        LAddress.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAddress.setForeground(new java.awt.Color(255, 255, 255));
        LAddress.setText("Address                 :");
        jPanel1.add(LAddress);
        LAddress.setBounds(20, 330, 110, 27);

        LEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email                      :");
        jPanel1.add(LEmail);
        LEmail.setBounds(20, 280, 110, 30);
        jPanel1.add(TFEmail);
        TFEmail.setBounds(150, 280, 266, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 560, 100, 32);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 560, 100, 32);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update Employee");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 11, 410, 59);

        TFAddress.setColumns(20);
        TFAddress.setLineWrap(true);
        TFAddress.setRows(5);
        TFAddress.setTabSize(4);
        jScrollPane1.setViewportView(TFAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 330, 260, 71);

        LDateofBirth.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LDateofBirth.setForeground(new java.awt.Color(255, 255, 255));
        LDateofBirth.setText("Date of Birth        :");
        jPanel1.add(LDateofBirth);
        LDateofBirth.setBounds(20, 130, 120, 30);
        jPanel1.add(DateOfBirth);
        DateOfBirth.setBounds(150, 130, 180, 30);

        LSalary.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LSalary.setForeground(new java.awt.Color(255, 255, 255));
        LSalary.setText("Salary                   :");
        LSalary.setToolTipText("");
        jPanel1.add(LSalary);
        LSalary.setBounds(20, 420, 110, 30);

        TFSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSalaryActionPerformed(evt);
            }
        });
        TFSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFSalaryKeyReleased(evt);
            }
        });
        jPanel1.add(TFSalary);
        TFSalary.setBounds(150, 420, 140, 30);

        LDateofJoining.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LDateofJoining.setForeground(new java.awt.Color(255, 255, 255));
        LDateofJoining.setText("Date of Joining   :");
        jPanel1.add(LDateofJoining);
        LDateofJoining.setBounds(20, 180, 120, 30);
        jPanel1.add(DateOfJoining);
        DateOfJoining.setBounds(150, 180, 180, 30);

        LSalary1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LSalary1.setForeground(new java.awt.Color(255, 255, 255));
        LSalary1.setText("Salary                   :");
        LSalary1.setToolTipText("");
        jPanel1.add(LSalary1);
        LSalary1.setBounds(20, 470, 110, 30);

        UERBActiveEmp.setBackground(new java.awt.Color(32, 37, 45));
        UERBActiveEmp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        UERBActiveEmp.setForeground(new java.awt.Color(255, 255, 255));
        UERBActiveEmp.setText("Active Employee");
        UERBActiveEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UERBActiveEmp.setRequestFocusEnabled(false);
        UERBActiveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UERBActiveEmpActionPerformed(evt);
            }
        });
        jPanel1.add(UERBActiveEmp);
        UERBActiveEmp.setBounds(150, 480, 130, 23);

        UERBNotWorking.setBackground(new java.awt.Color(32, 37, 45));
        UERBNotWorking.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        UERBNotWorking.setForeground(new java.awt.Color(255, 255, 255));
        UERBNotWorking.setText("Not Working");
        UERBNotWorking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UERBNotWorking.setRequestFocusEnabled(false);
        UERBNotWorking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UERBNotWorkingActionPerformed(evt);
            }
        });
        jPanel1.add(UERBNotWorking);
        UERBNotWorking.setBounds(150, 510, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DB.EditEmployeeCount = 0;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TFMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMobileNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFMobileNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Taking Inputs To Variables
        String[] NewPerson = new String[9];
        NewPerson[0] = TFCustomerName.getText();
        long temp = 0;
        try {
            temp = Long.parseLong(TFMobileNo.getText());
            NewPerson[1] = String.valueOf(temp);
        } catch (NumberFormatException numberFormatException) {
            NewPerson[1] = "";
        }
        
        NewPerson[2] = TFEmail.getText();
        NewPerson[3] = TFAddress.getText();
        NewPerson[4] = TFSalary.getText();
        try {
            NewPerson[5] = dateFormat.format(DateOfBirth.getDate());
        } catch (Exception e) {
            NewPerson[5] = "";
        }
        try {
            NewPerson[6] = dateFormat.format(DateOfJoining.getDate());
        } catch (Exception e) {
            NewPerson[6] = "";
        }
        
        NewPerson[8] = this.EmpID;
        
        if(UERBActiveEmp.isSelected())
        {
            ActiveEmp = String.valueOf(true);
        }else{
            ActiveEmp = String.valueOf(false);
        }
        NewPerson[7] = ActiveEmp;
                
        for(int i=0;i<NewPerson.length;i++)
        {
            NewPerson[i].trim();
        }
        
        
        int count = 0;
        try {
            count = db.NewEmployeeName(NewPerson[0]);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(count <= 1)
        {
            //Validation
            if(NewPerson[0] == null || NewPerson[0].equals(""))
            {
                LPersonName.setForeground(Color.red);
            }else if(NewPerson[5] == null || NewPerson[5].equals("")){
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.red);
            }else if(NewPerson[5] == null || NewPerson[5].equals("")){
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.red);
                LDateofJoining.setForeground(Color.red);
            }else if(NewPerson[1].length() != 10)
            {
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.WHITE);
                LDateofJoining.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.red);
            }else if(NewPerson[2] == null || NewPerson[2].equals("")){
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.WHITE);
                LDateofJoining.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.red);
            }else if(NewPerson[3] == null || NewPerson[3].equals("")){
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.WHITE);
                LDateofJoining.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.red);
            }else if(NewPerson[4] == null || NewPerson[4].equals("")){
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.WHITE);
                LDateofJoining.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LSalary.setForeground(Color.red);
            }else{
                LPersonName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LDateofBirth.setForeground(Color.WHITE);
                LDateofJoining.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LSalary.setForeground(Color.WHITE);
                try {
                    db.UpdateEmployeeEntry(NewPerson);
                    JOptionPane.showMessageDialog(null, "Saved Successfully!");
                    DB.EditEmployeeCount = 0;
                    DB.RefreshEAEmployeeTable();
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(UpdateEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Name Already Exist in Database");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFCustomerNameKeyReleased
        // TODO add your handling code here:
        String name = TFCustomerName.getText();
        boolean valid = (name != null) && pattern.matcher(name).matches();
        if(!valid)
        {
            try {
                name = name.substring(0, name.length() - 1);
            } catch (Exception e) {
            }
            TFCustomerName.setText(name);
        }
    }//GEN-LAST:event_TFCustomerNameKeyReleased

    private void TFMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMobileNoKeyReleased
        // TODO add your handling code here:
        String MobileNo = TFMobileNo.getText();
        boolean valid = (MobileNo != null) && pattern2.matcher(MobileNo).matches();
        if(!valid)
        {
            try {
                MobileNo = MobileNo.substring(0, MobileNo.length() - 1);
            } catch (Exception e) {
            }
            TFMobileNo.setText(MobileNo);
        }
    }//GEN-LAST:event_TFMobileNoKeyReleased

    private void TFSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalaryActionPerformed

    private void TFSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSalaryKeyReleased
        // TODO add your handling code here:
        String Salary = TFSalary.getText();
        boolean valid = (Salary != null) && pattern2.matcher(Salary).matches();
        if(!valid)
        {
            try {
                Salary = Salary.substring(0, Salary.length() - 1);
            } catch (Exception e) {
            }
            TFSalary.setText(Salary);
        }
    }//GEN-LAST:event_TFSalaryKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        DB.EditEmployeeCount = 0;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void UERBActiveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UERBActiveEmpActionPerformed
        // TODO add your handling code here:
        ActiveEmp = "true";
    }//GEN-LAST:event_UERBActiveEmpActionPerformed

    private void UERBNotWorkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UERBNotWorkingActionPerformed
        // TODO add your handling code here:
        ActiveEmp = "false";
    }//GEN-LAST:event_UERBNotWorkingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateOfBirth;
    private com.toedter.calendar.JDateChooser DateOfJoining;
    private javax.swing.JLabel LAddress;
    private javax.swing.JLabel LDateofBirth;
    private javax.swing.JLabel LDateofJoining;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LMobileNo;
    private javax.swing.JLabel LPersonName;
    private javax.swing.JLabel LSalary;
    private javax.swing.JLabel LSalary1;
    private javax.swing.JTextArea TFAddress;
    private javax.swing.JTextField TFCustomerName;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFMobileNo;
    private javax.swing.JTextField TFSalary;
    private javax.swing.JRadioButton UERBActiveEmp;
    private javax.swing.JRadioButton UERBNotWorking;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
