/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

/**
 *
 * @author user
 */
import Database.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
//import javafx.beans.binding.DoubleBinding;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class UpdateSupplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    UpdateSupplier USP;
    DatabaseConnection db;
    DashBoard DB;
    String[] SupplierD = new String[9];
    String SupplierID;
    String WPanel;
    
    Pattern pattern = Pattern.compile("[A-Za-z0-9_ ]+");
    Pattern pattern2 = Pattern.compile("[0-9]+");
    Pattern pattern3 = Pattern.compile("[A-Z0-9]+");
    public UpdateSupplier(String SupplierID,String WPanel,DashBoard DB) throws SQLException {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("InventoryImage.png")));
        db = new DatabaseConnection(InventorySystem.con);
        this.DB = DB;
        this.SupplierID = SupplierID;
        this.DB.VSupplierUCount = 1;
        USP = this;
        this.WPanel = WPanel;
        
        SupplierD = db.getSupplierDforUpdate(SupplierID);
        TFSupplierName.setText(SupplierD[0]);
        TFMobileNo.setText(SupplierD[1]);
        TFEmail.setText(SupplierD[2]);
        TFAddress.setText(SupplierD[3]);
        TFGSTINNo.setText(SupplierD[4]);
        TFAadharNo.setText(SupplierD[5]);
        TFPreDue.setText(SupplierD[6]);
        TFDue.setText("0");
        USP = this;
    }

    private UpdateSupplier() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LSupplierName = new javax.swing.JLabel();
        TFSupplierName = new javax.swing.JTextField();
        LMobileNo = new javax.swing.JLabel();
        TFMobileNo = new javax.swing.JTextField();
        LAadharNo = new javax.swing.JLabel();
        LGSTINNo = new javax.swing.JLabel();
        LAddress = new javax.swing.JLabel();
        LEmail = new javax.swing.JLabel();
        TFEmail = new javax.swing.JTextField();
        TFGSTINNo = new javax.swing.JTextField();
        TFAadharNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFAddress = new javax.swing.JTextArea();
        LDue = new javax.swing.JLabel();
        TFDue = new javax.swing.JTextField();
        LPreDue = new javax.swing.JLabel();
        TFPreDue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 37, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(465, 539));
        jPanel1.setLayout(null);

        LSupplierName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LSupplierName.setForeground(new java.awt.Color(255, 255, 255));
        LSupplierName.setText("Spplier Name      :");
        LSupplierName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(LSupplierName);
        LSupplierName.setBounds(20, 80, 110, 31);

        TFSupplierName.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFSupplierNameKeyReleased(evt);
            }
        });
        jPanel1.add(TFSupplierName);
        TFSupplierName.setBounds(150, 80, 270, 27);

        LMobileNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LMobileNo.setForeground(new java.awt.Color(255, 255, 255));
        LMobileNo.setText("Mobile No.           :");
        LMobileNo.setToolTipText("");
        jPanel1.add(LMobileNo);
        LMobileNo.setBounds(20, 140, 107, 20);

        TFMobileNo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFMobileNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFMobileNo);
        TFMobileNo.setBounds(150, 130, 270, 28);

        LAadharNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAadharNo.setForeground(new java.awt.Color(255, 255, 255));
        LAadharNo.setText("Aadhar No           :");
        jPanel1.add(LAadharNo);
        LAadharNo.setBounds(20, 380, 110, 31);

        LGSTINNo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LGSTINNo.setForeground(new java.awt.Color(255, 255, 255));
        LGSTINNo.setText("GSTIN No            :");
        jPanel1.add(LGSTINNo);
        LGSTINNo.setBounds(20, 330, 110, 26);

        LAddress.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LAddress.setForeground(new java.awt.Color(255, 255, 255));
        LAddress.setText("Address                 :");
        jPanel1.add(LAddress);
        LAddress.setBounds(20, 230, 110, 27);

        LEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 255, 255));
        LEmail.setText("Email                      :");
        jPanel1.add(LEmail);
        LEmail.setBounds(20, 180, 110, 31);

        TFEmail.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(TFEmail);
        TFEmail.setBounds(150, 180, 266, 28);

        TFGSTINNo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFGSTINNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFGSTINNoKeyReleased(evt);
            }
        });
        jPanel1.add(TFGSTINNo);
        TFGSTINNo.setBounds(150, 330, 266, 27);

        TFAadharNo.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(TFAadharNo);
        TFAadharNo.setBounds(150, 380, 265, 27);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 480, 100, 32);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 480, 100, 32);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE SUPPLIER");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(25, 11, 410, 59);

        TFAddress.setColumns(20);
        TFAddress.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFAddress.setLineWrap(true);
        TFAddress.setRows(5);
        TFAddress.setTabSize(4);
        jScrollPane1.setViewportView(TFAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 230, 260, 71);

        LDue.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LDue.setForeground(new java.awt.Color(255, 255, 255));
        LDue.setText("Pay Due                :");
        jPanel1.add(LDue);
        LDue.setBounds(20, 430, 110, 31);

        TFDue.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFDue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDueKeyReleased(evt);
            }
        });
        jPanel1.add(TFDue);
        TFDue.setBounds(150, 430, 80, 27);

        LPreDue.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        LPreDue.setForeground(new java.awt.Color(255, 255, 255));
        LPreDue.setText("PreDue     :");
        jPanel1.add(LPreDue);
        LPreDue.setBounds(250, 430, 70, 31);

        TFPreDue.setEditable(false);
        TFPreDue.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        TFPreDue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFPreDueKeyReleased(evt);
            }
        });
        jPanel1.add(TFPreDue);
        TFPreDue.setBounds(330, 430, 80, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 465, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.DB.VSupplierUCount = 0;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] Supplier = new String[8];
        Supplier[0] = TFSupplierName.getText();
        long temp = 0;
        try {
            temp = Long.parseLong(TFMobileNo.getText());
            Supplier[1] = String.valueOf(temp);
        } catch (NumberFormatException numberFormatException) {
            Supplier[1] = "";
        }
        
        Supplier[2] = TFEmail.getText();
        Supplier[3] = TFAddress.getText();
        Supplier[4] = TFGSTINNo.getText();
        Supplier[5] = TFAadharNo.getText();
        Supplier[6] = SupplierID;
        double PreDue = Double.valueOf(TFPreDue.getText());
        double Due = Double.valueOf(TFDue.getText());
        double RDue = PreDue - Due;
        if(Due <= PreDue && Due >= 0)
        {
            Supplier[7] = String.valueOf(RDue);
            for(int i=0;i<Supplier.length;i++)
            {
                Supplier[i].trim();
            }

            if(Supplier[0] == null || Supplier[0].equals(""))
            {
                LSupplierName.setForeground(Color.red);
            }else if(Supplier[1].length() != 10)
            {
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.red);
            }else if(Supplier[2] == null || Supplier[2].equals(""))
            {
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.red);
            }else if(Supplier[3] == null || Supplier[3].equals(""))
            {
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.red);
            }else if(Supplier[4].length() != 15)
            {
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LGSTINNo.setForeground(Color.red);
            }else if(Supplier[5].length() != 12)
            {
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LGSTINNo.setForeground(Color.WHITE);
                LAadharNo.setForeground(Color.red);
            }else if(TFDue.getText() == null || TFDue.getText().equals("")){
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LGSTINNo.setForeground(Color.WHITE);
                LAadharNo.setForeground(Color.WHITE);
                LDue.setForeground(Color.red);
            }
            else{
                LSupplierName.setForeground(Color.WHITE);
                LMobileNo.setForeground(Color.WHITE);
                LEmail.setForeground(Color.WHITE);
                LAddress.setForeground(Color.WHITE);
                LGSTINNo.setForeground(Color.WHITE);
                LAadharNo.setForeground(Color.WHITE);
                LDue.setForeground(Color.WHITE);
                try {
                    db.SupplierUpdate(Supplier);
                    String[] TransactionD = new String[4];
                    TransactionD[0] = Supplier[0];
                    TransactionD[1] = "Supplier";
                    TransactionD[2] = "Given";
                    TransactionD[3] = TFDue.getText();
                    db.TransactionTable(TransactionD);
                    JOptionPane.showMessageDialog(null, "Supplier Details Updated Successfully");
                    this.DB.VSupplierUCount = 0;
                    USP.setVisible(false);
                    if (WPanel.equals("ViewSupplier")) {
                        this.DB.VSCheckBoxandTableRefresh();
                    }else{
                        this.DB.PRCheckBoxandTableRefresh();
                    }
                    this.dispose();
                } catch (SQLException ex) {
                    Logger.getLogger(UpdateSupplier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            LDue.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Entered Value is more then PreDue");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFDueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDueKeyReleased
        // TODO add your handling code here:
        String due = TFDue.getText();
        try {
            double temp = Double.valueOf(due);
            LDue.setForeground(Color.WHITE);
        } catch (Exception e) {
            LDue.setForeground(Color.red);
        }
    }//GEN-LAST:event_TFDueKeyReleased

    private void TFPreDueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPreDueKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPreDueKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.DB.VSupplierUCount = 0;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void TFSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSupplierNameKeyReleased
        // TODO add your handling code here:
        String name = TFSupplierName.getText();
        boolean valid = (name != null) && pattern.matcher(name).matches();
        if(!valid)
        {
            try {
                name = name.substring(0, name.length() - 1);
            } catch (Exception e) {
            }
            TFSupplierName.setText(name);
        }
    }//GEN-LAST:event_TFSupplierNameKeyReleased

    private void TFMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMobileNoKeyReleased
        // TODO add your handling code here:
        String MobileNo = TFMobileNo.getText();
        boolean valid = (MobileNo != null) && pattern2.matcher(MobileNo).matches();
        if(!valid)
        {
            try {
                MobileNo = MobileNo.substring(0, MobileNo.length() - 1);
            } catch (Exception e) {
            }
            TFMobileNo.setText(MobileNo);
        }
    }//GEN-LAST:event_TFMobileNoKeyReleased

    private void TFGSTINNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFGSTINNoKeyReleased
        // TODO add your handling code here:
        String GSTINNo = TFGSTINNo.getText();
        boolean valid = (GSTINNo != null) && pattern3.matcher(GSTINNo).matches();
        if(!valid)
        {
            try {
                GSTINNo = GSTINNo.substring(0, GSTINNo.length() - 1);
            } catch (Exception e) {
            }
            TFGSTINNo.setText(GSTINNo);
        }
    }//GEN-LAST:event_TFGSTINNoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAadharNo;
    private javax.swing.JLabel LAddress;
    private javax.swing.JLabel LDue;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LGSTINNo;
    private javax.swing.JLabel LMobileNo;
    private javax.swing.JLabel LPreDue;
    private javax.swing.JLabel LSupplierName;
    private javax.swing.JTextField TFAadharNo;
    private javax.swing.JTextArea TFAddress;
    private javax.swing.JTextField TFDue;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFGSTINNo;
    private javax.swing.JTextField TFMobileNo;
    private javax.swing.JTextField TFPreDue;
    private javax.swing.JTextField TFSupplierName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
